name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    name: Build and Publish Storybook
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build Storybook
        run: npm run build-storybook

      - name: Verify build output
        run: |
          echo "Checking storybook-static directory:"
          ls -la storybook-static/ || echo "storybook-static directory doesn't exist"
          echo "Current directory contents:"
          ls -la

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Success notification
        run: |
          echo "=========================================="
          echo "🎉 Storybook 9 successfully published!"
          echo "📖 URL: ${{ steps.deployment.outputs.page_url }}"
          echo "=========================================="
